### ISSUE TITLE
tensorflow nil operation r1.11

### ISSUE THREAD

**Issue by AhmedX6** [plutov/packagemain#3]
Hello,

I'm using Tensorflow r1.11. I built C API with bazel, everything went good.
I did a test `go test github.com/tensorflow/tensorflow/tensorflow/go` and it went "ok" too.

Then I tried your code but I have an error : 
panic: nil-Operation. If the Output was created with a Scope object, see Scope.Err() for details.

```
goroutine 1 [running]:
github.com/tensorflow/tensorflow/tensorflow/go.Output.c(0x0, 0x0, 0x0, 0x0)
        /home/ahmedx6/go/src/github.com/tensorflow/tensorflow/tensorflow/go/operation.go:130 +0x75
github.com/tensorflow/tensorflow/tensorflow/go.newCRunArgs(0xc420067e78, 0xc420067de0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
        /home/ahmedx6/go/src/github.com/tensorflow/tensorflow/tensorflow/go/session.go:356 +0x23d
github.com/tensorflow/tensorflow/tensorflow/go.(*Session).Run(0xc42039e140, 0xc420067e78, 0xc420067de0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/ahmedx6/go/src/github.com/tensorflow/tensorflow/tensorflow/go/session.go:130 +0x130
main.main()
        /home/ahmedx6/go/recognize.go:68 +0x53a
```

Here is the command I'm trying with a dataset of flowers : `./recognize https://fr.cdn.v5.futura-sciences.com/buildsv6/images/wide1920/8/d/f/8dfb5138be_98819_culture-tournesol.jpg`

Can you please help me ?

**Comment by AhmedX6** [comment]
Resolved by replacing the input and ouput graph layer by mine... I forgot that point sorry !
